version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: ['npm', 'run', 'dev']
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - .:/app

