FROM node:15.5.1 as builder

RUN apt-get update -y

WORKDIR /app

COPY package.json .

COPY package-lock.json .

RUN npm i --only=production

COPY . .

RUN npm i --only=development

RUN npm test

FROM node:15.5.1

RUN apt-get update -y

WORKDIR /app

COPY --from=builder /app/package.json package.json

RUN cat package.json

COPY package-lock.json .

RUN npm i --only=production

COPY . .

EXPOSE 5000

CMD [ "npm", "start" ]
